name: Docs

on:
  push:
  pull_request:

jobs:
  mdbook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mdBook
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook

      - name: Build docs
        run: mdbook build docs

